version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - Tech debt
  ignore:
  - dependency-name: aws-sdk-s3
    versions:
    - 1.88.0
    - 1.88.1
    - 1.88.2
    - 1.90.0
    - 1.92.0
    - 1.93.0
    - 1.93.1
  - dependency-name: stripe
    versions:
    - 5.30.0
    - 5.31.0
  - dependency-name: sidekiq
    versions:
    - 6.2.0
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
  - dependency-name: pry
    versions:
    - 0.14.0
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: webmock
    versions:
    - 3.11.2
    - 3.11.3
    - 3.12.0
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.9.0
    - 1.9.1
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: database_cleaner
    versions:
    - 2.0.0
  - dependency-name: capybara
    versions:
    - 3.35.1
  - dependency-name: ibm_watson
    versions:
    - 2.0.0
